name = "spoke_tcp"
version = "1.0.0"

description = "A TCP transport channel for the spoke MQTT client."
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "spoke" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
mug = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glisten = ">= 7.0.0 and < 8.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"
