name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mqtt-broker:
        image: emqx
        ports:
          - 1883:1883
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.7.0-rc3"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam run -m integration_tests
      - run: gleam format --check src test
